// let age = window.prompt("How old are you");
// age = Number(age);
// age += 1;
// console.log(age);
let x;
let y;
let z;
x = Number(3.14);
y = String("hello");
z = Boolean("pizza");
console.log(x, typeof x);
console.log(y, typeof y);
console.log(z, typeof z);
